[package]
name = "quiketc"
version = "2.0.0"
authors = ["Zayne64 <11258171+Zayne64@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"